# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional lora-adapter and lora-redis services
# for the SupeMQ platform. Since this services are optional, this file is dependent on the
# docker-compose.yml file from <project_root>/docker/. In order to run these services,
# core services, as well as the network from the core composition, should be already running.

networks:
  supermq-base-net:

services:
  lora-redis:
    image: redis:7.2.4-alpine
    container_name: supermq-contrib-lora-redis
    restart: on-failure
    networks:
      - supermq-base-net

  lora-adapter:
    image: supermq-contrib/lora:${SMQ_RELEASE_TAG}
    container_name: supermq-contrib-lora
    restart: on-failure
    environment:
      SMQ_LORA_ADAPTER_LOG_LEVEL: ${SMQ_LORA_ADAPTER_LOG_LEVEL}
      SMQ_LORA_ADAPTER_MESSAGES_URL: ${SMQ_LORA_ADAPTER_MESSAGES_URL}
      SMQ_LORA_ADAPTER_MESSAGES_TOPIC: ${SMQ_LORA_ADAPTER_MESSAGES_TOPIC}
      SMQ_LORA_ADAPTER_MESSAGES_USER: ${SMQ_LORA_ADAPTER_MESSAGES_USER}
      SMQ_LORA_ADAPTER_MESSAGES_PASS: ${SMQ_LORA_ADAPTER_MESSAGES_PASS}
      SMQ_LORA_ADAPTER_MESSAGES_TIMEOUT: ${SMQ_LORA_ADAPTER_MESSAGES_TIMEOUT}
      SMQ_LORA_ADAPTER_EVENT_CONSUMER: ${SMQ_LORA_ADAPTER_EVENT_CONSUMER}
      SMQ_LORA_ADAPTER_HTTP_HOST: ${SMQ_LORA_ADAPTER_HTTP_HOST}
      SMQ_LORA_ADAPTER_HTTP_PORT: ${SMQ_LORA_ADAPTER_HTTP_PORT}
      SMQ_LORA_ADAPTER_HTTP_SERVER_CERT: ${SMQ_LORA_ADAPTER_HTTP_SERVER_CERT}
      SMQ_LORA_ADAPTER_HTTP_SERVER_KEY: ${SMQ_LORA_ADAPTER_HTTP_SERVER_KEY}
      SMQ_LORA_ADAPTER_ROUTE_MAP_URL: ${SMQ_LORA_ADAPTER_ROUTE_MAP_URL}
      SMQ_ES_URL: ${SMQ_ES_URL}
      SMQ_MESSAGE_BROKER_URL: ${SMQ_MESSAGE_BROKER_URL}
      SMQ_JAEGER_URL: ${SMQ_JAEGER_URL}
      SMQ_JAEGER_TRACE_RATIO: ${SMQ_JAEGER_TRACE_RATIO}
      SMQ_SEND_TELEMETRY: ${SMQ_SEND_TELEMETRY}
      SMQ_LORA_ADAPTER_INSTANCE_ID: ${SMQ_LORA_ADAPTER_INSTANCE_ID}
    ports:
      - ${SMQ_LORA_ADAPTER_HTTP_PORT}:${SMQ_LORA_ADAPTER_HTTP_PORT}
    networks:
      - supermq-base-net
