# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional InfluxDB and InfluxDB-writer services
# for the SupeMQ platform. Since this services are optional, this file is dependent on the
# docker-compose.yml file from <project_root>/docker/. In order to run these services,
# core services, as well as the network from the core composition, should be already running.

networks:
  supermq-base-net:

volumes:
  supermq-contrib-influxdb-volume:

services:
  influxdb:
    image: influxdb:2.7.5-alpine
    container_name: supermq-contrib-influxdb
    restart: on-failure
    environment:
      DOCKER_INFLUXDB_INIT_MODE: ${SMQ_INFLUXDB_INIT_MODE}
      DOCKER_INFLUXDB_INIT_USERNAME: ${SMQ_INFLUXDB_ADMIN_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${SMQ_INFLUXDB_ADMIN_PASSWORD}
      DOCKER_INFLUXDB_ADMIN_URL: ${SMQ_INFLUXDB_ADMIN_URL}
      DOCKER_INFLUXDB_INIT_ORG: ${SMQ_INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${SMQ_INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${SMQ_INFLUXDB_TOKEN}
      INFLUXDB_HTTP_FLUX_ENABLED: ${SMQ_INFLUXDB_HTTP_ENABLED}
    networks:
      - supermq-base-net
    ports:
      - ${SMQ_INFLUXDB_PORT}:${SMQ_INFLUXDB_PORT}
    volumes:
      - supermq-contrib-influxdb-volume:/var/lib/influxdb2

  influxdb-writer:
    image: supermq-contrib/influxdb-writer:${SMQ_RELEASE_TAG}
    container_name: supermq-contrib-influxdb-writer
    depends_on:
      - influxdb
    restart: on-failure
    environment:
      SMQ_INFLUX_WRITER_LOG_LEVEL: ${SMQ_INFLUX_WRITER_LOG_LEVEL}
      SMQ_INFLUX_WRITER_CONFIG_PATH: ${SMQ_INFLUX_WRITER_CONFIG_PATH}
      SMQ_INFLUX_WRITER_HTTP_HOST: ${SMQ_INFLUX_WRITER_HTTP_HOST}
      SMQ_INFLUX_WRITER_HTTP_PORT: ${SMQ_INFLUX_WRITER_HTTP_PORT}
      SMQ_INFLUX_WRITER_HTTP_SERVER_CERT: ${SMQ_INFLUX_WRITER_HTTP_SERVER_CERT}
      SMQ_INFLUX_WRITER_HTTP_SERVER_KEY: ${SMQ_INFLUX_WRITER_HTTP_SERVER_KEY}
      SMQ_INFLUXDB_PROTOCOL: ${SMQ_INFLUXDB_PROTOCOL}
      SMQ_INFLUXDB_HOST: ${SMQ_INFLUXDB_HOST}
      SMQ_INFLUXDB_PORT: ${SMQ_INFLUXDB_PORT}
      SMQ_INFLUXDB_ADMIN_USER: ${SMQ_INFLUXDB_ADMIN_USER}
      SMQ_INFLUXDB_ADMIN_PASSWORD: ${SMQ_INFLUXDB_ADMIN_PASSWORD}
      SMQ_INFLUXDB_NAME: ${SMQ_INFLUXDB_NAME}
      SMQ_INFLUXDB_BUCKET: ${SMQ_INFLUXDB_BUCKET}
      SMQ_INFLUXDB_ORG: ${SMQ_INFLUXDB_ORG}
      SMQ_INFLUXDB_TOKEN: ${SMQ_INFLUXDB_TOKEN}
      SMQ_INFLUXDB_DBURL: ${SMQ_INFLUXDB_DBURL}
      SMQ_INFLUXDB_USER_AGENT: ${SMQ_INFLUXDB_USER_AGENT}
      SMQ_INFLUXDB_TIMEOUT: ${SMQ_INFLUXDB_TIMEOUT}
      SMQ_INFLUXDB_INSECURE_SKIP_VERIFY: ${SMQ_INFLUXDB_INSECURE_SKIP_VERIFY}
      SMQ_MESSAGE_BROKER_URL: ${SMQ_MESSAGE_BROKER_URL}
      SMQ_JAEGER_URL: ${SMQ_JAEGER_URL}
      SMQ_JAEGER_TRACE_RATIO: ${SMQ_JAEGER_TRACE_RATIO}
      SMQ_SEND_TELEMETRY: ${SMQ_SEND_TELEMETRY}
      SMQ_INFLUX_WRITER_INSTANCE_ID: ${SMQ_INFLUX_WRITER_INSTANCE_ID}
    ports:
      - ${SMQ_INFLUX_WRITER_HTTP_PORT}:${SMQ_INFLUX_WRITER_HTTP_PORT}
    networks:
      - supermq-base-net
    volumes:
      - ./config.toml:/config.toml
