# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

pkgname: mocks
mockname: "{{.InterfaceName}}"
filename: "{{snakecase .InterfaceName}}.go"
dir: "{{.InterfaceDirRelative}}/mocks"
template-data:
  boilerplate-file: ./tools/config/boilerplate.txt
  with-expecter: true
force-file-write: true

packages:
  github.com/absmach/supermq-contrib/consumers/notifiers:
    interfaces:
      SubscriptionsRepository:
      Service:

  github.com/absmach/supermq-contrib/lora:
    interfaces:
      RouteMapRepository:

  github.com/absmach/supermq-contrib/twins:
    interfaces:
      TwinRepository:
      TwinCache:
      Service:
      StateRepository:

