# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional opcua-adapter and opcua-redis services
# for the SupeMQ platform. Since this services are optional, this file is dependent on the
# docker-compose.yml file from <project_root>/docker/. In order to run these services,
# core services, as well as the network from the core composition, should be already running.

networks:
  supermq-base-net:

volumes:
  supermq-contrib-opcua-adapter-volume:
  supermq-contrib-opcua-redis-volume:

services:
  opcua-redis:
    image: redis:7.2.4-alpine
    container_name: supermq-contrib-opcua-redis
    restart: on-failure
    networks:
      - supermq-base-net
    volumes:
      - supermq-contrib-opcua-redis-volume:/data

  opcua-adapter:
    image: supermq-contrib/opcua:${SMQ_RELEASE_TAG}
    container_name: supermq-contrib-opcua
    restart: on-failure
    environment:
      SMQ_OPCUA_ADAPTER_LOG_LEVEL: ${SMQ_OPCUA_ADAPTER_LOG_LEVEL}
      SMQ_OPCUA_ADAPTER_EVENT_CONSUMER: ${SMQ_OPCUA_ADAPTER_EVENT_CONSUMER}
      SMQ_OPCUA_ADAPTER_HTTP_HOST: ${SMQ_OPCUA_ADAPTER_HTTP_HOST}
      SMQ_OPCUA_ADAPTER_HTTP_PORT: ${SMQ_OPCUA_ADAPTER_HTTP_PORT}
      SMQ_OPCUA_ADAPTER_HTTP_SERVER_CERT: ${SMQ_OPCUA_ADAPTER_HTTP_SERVER_CERT}
      SMQ_OPCUA_ADAPTER_HTTP_SERVER_KEY: ${SMQ_OPCUA_ADAPTER_HTTP_SERVER_KEY}
      SMQ_ES_URL: ${SMQ_ES_URL}
      SMQ_OPCUA_ADAPTER_ROUTE_MAP_URL: ${SMQ_OPCUA_ADAPTER_ROUTE_MAP_URL}
      SMQ_MESSAGE_BROKER_URL: ${SMQ_MESSAGE_BROKER_URL}
      SMQ_JAEGER_URL: ${SMQ_JAEGER_URL}
      SMQ_JAEGER_TRACE_RATIO: ${SMQ_JAEGER_TRACE_RATIO}
      SMQ_SEND_TELEMETRY: ${SMQ_SEND_TELEMETRY}
      SMQ_OPCUA_ADAPTER_INSTANCE_ID: ${SMQ_OPCUA_ADAPTER_INSTANCE_ID}
    ports:
      - ${SMQ_OPCUA_ADAPTER_HTTP_PORT}:${SMQ_OPCUA_ADAPTER_HTTP_PORT}
    networks:
      - supermq-base-net
    volumes:
      - supermq-contrib-opcua-adapter-volume:/store
