# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional Cassandra and cassandra-writer. Since these are optional, this file is
# dependent of docker-compose file from <project_root>/docker. In order to run these services, execute command:
# docker compose -f docker/docker-compose.yml -f docker/addons/cassandra-writer/docker-compose.yml up
# from project root.

networks:
  supermq-base-net:

volumes:
  supermq-cassandra-volume:

services:
  cassandra:
    image: cassandra:3.11.16
    container_name: supermq-cassandra
    restart: on-failure
    networks:
      - supermq-base-net
    ports:
      - ${SMQ_CASSANDRA_PORT}:${SMQ_CASSANDRA_PORT}
    volumes:
      - supermq-cassandra-volume:/var/lib/cassandra

  cassandra-init-keyspace:
    image: cassandra:3.11.16
    depends_on:
      - cassandra
    restart: on-failure
    volumes:
      - ./init.sh:/init.sh
    entrypoint: ["/init.sh"]
    networks:
      - supermq-base-net

  cassandra-writer:
    image: supermq/cassandra-writer:${SMQ_RELEASE_TAG}
    container_name: supermq-cassandra-writer
    depends_on:
      - cassandra
    restart: on-failure
    environment:
      SMQ_CASSANDRA_WRITER_LOG_LEVEL: ${SMQ_CASSANDRA_WRITER_LOG_LEVEL}
      SMQ_CASSANDRA_WRITER_CONFIG_PATH: ${SMQ_CASSANDRA_WRITER_CONFIG_PATH}
      SMQ_CASSANDRA_WRITER_HTTP_HOST: ${SMQ_CASSANDRA_WRITER_HTTP_HOST}
      SMQ_CASSANDRA_WRITER_HTTP_PORT: ${SMQ_CASSANDRA_WRITER_HTTP_PORT}
      SMQ_CASSANDRA_WRITER_HTTP_SERVER_CERT: ${SMQ_CASSANDRA_WRITER_HTTP_SERVER_CERT}
      SMQ_CASSANDRA_WRITER_HTTP_SERVER_KEY: ${SMQ_CASSANDRA_WRITER_HTTP_SERVER_KEY}
      SMQ_CASSANDRA_PORT: ${SMQ_CASSANDRA_PORT}
      SMQ_CASSANDRA_CLUSTER: ${SMQ_CASSANDRA_CLUSTER}
      SMQ_CASSANDRA_KEYSPACE: ${SMQ_CASSANDRA_KEYSPACE}
      SMQ_CASSANDRA_USER: ${SMQ_CASSANDRA_USER}
      SMQ_CASSANDRA_PASS: ${SMQ_CASSANDRA_PASS}
      SMQ_MESSAGE_BROKER_URL: ${SMQ_MESSAGE_BROKER_URL}
      SMQ_JAEGER_URL: ${SMQ_JAEGER_URL}
      SMQ_JAEGER_TRACE_RATIO: ${SMQ_JAEGER_TRACE_RATIO}
      SMQ_SEND_TELEMETRY: ${SMQ_SEND_TELEMETRY}
      SMQ_CASSANDRA_WRITER_INSTANCE_ID: ${SMQ_CASSANDRA_WRITER_INSTANCE_ID}
    ports:
      - ${SMQ_CASSANDRA_WRITER_HTTP_PORT}:${SMQ_CASSANDRA_WRITER_HTTP_PORT}
    networks:
      - supermq-base-net
    volumes:
      - ./config.toml:/config.toml
