# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional InfluxDB and InfluxDB-writer services
# for the SupeMQ platform. Since this services are optional, this file is dependent on the
# docker-compose.yml file from <project_root>/docker/. In order to run these services,
# core services, as well as the network from the core composition, should be already running.

networks:
  supermq-base-net:
    driver: bridge

volumes:
  supermq-contrib-smtp-notifier-volume:

services:
  smtp-notifier-db:
    image: postgres:16.2-alpine
    container_name: supermq-contrib-smtp-notifier-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${SMQ_SMTP_NOTIFIER_DB_USER}
      POSTGRES_PASSWORD: ${SMQ_SMTP_NOTIFIER_DB_PASS}
      POSTGRES_DB: ${SMQ_SMTP_NOTIFIER_DB_NAME}
    networks:
      - supermq-base-net
    volumes:
      - supermq-contrib-smtp-notifier-volume:/var/lib/postgresql/datab

  smtp-notifier:
    image: supermq-contrib/smtp-notifier:latest
    container_name: supermq-contrib-smtp-notifier
    depends_on:
      - smtp-notifier-db
    restart: on-failure
    environment:
      SMQ_SMTP_NOTIFIER_LOG_LEVEL: ${SMQ_SMTP_NOTIFIER_LOG_LEVEL}
      SMQ_SMTP_NOTIFIER_FROM_ADDR: ${SMQ_SMTP_NOTIFIER_FROM_ADDR}]
      SMQ_SMTP_NOTIFIER_CONFIG_PATH: ${SMQ_SMTP_NOTIFIER_CONFIG_PATH}
      SMQ_SMTP_NOTIFIER_HTTP_HOST: ${SMQ_SMTP_NOTIFIER_HTTP_HOST}
      SMQ_SMTP_NOTIFIER_HTTP_PORT: ${SMQ_SMTP_NOTIFIER_HTTP_PORT}
      SMQ_SMTP_NOTIFIER_HTTP_SERVER_CERT: ${SMQ_SMTP_NOTIFIER_HTTP_SERVER_CERT}
      SMQ_SMTP_NOTIFIER_HTTP_SERVER_KEY: ${SMQ_SMTP_NOTIFIER_HTTP_SERVER_KEY}
      SMQ_SMTP_NOTIFIER_DB_HOST: ${SMQ_SMTP_NOTIFIER_DB_HOST}
      SMQ_SMTP_NOTIFIER_DB_PORT: ${SMQ_SMTP_NOTIFIER_DB_PORT}
      SMQ_SMTP_NOTIFIER_DB_USER: ${SMQ_SMTP_NOTIFIER_DB_USER}
      SMQ_SMTP_NOTIFIER_DB_PASS: ${SMQ_SMTP_NOTIFIER_DB_PASS}
      SMQ_SMTP_NOTIFIER_DB_NAME: ${SMQ_SMTP_NOTIFIER_DB_NAME}
      SMQ_SMTP_NOTIFIER_DB_SSL_MODE: ${SMQ_SMTP_NOTIFIER_DB_SSL_MODE}
      SMQ_SMTP_NOTIFIER_DB_SSL_CERT: ${SMQ_SMTP_NOTIFIER_DB_SSL_CERT}
      SMQ_SMTP_NOTIFIER_DB_SSL_KEY: ${SMQ_SMTP_NOTIFIER_DB_SSL_KEY}
      SMQ_SMTP_NOTIFIER_DB_SSL_ROOT_CERT: ${SMQ_SMTP_NOTIFIER_DB_SSL_ROOT_CERT}
      SMQ_AUTH_GRPC_URL: ${SMQ_AUTH_GRPC_URL}
      SMQ_AUTH_GRPC_TIMEOUT: ${SMQ_AUTH_GRPC_TIMEOUT}
      SMQ_AUTH_GRPC_CLIENT_CERT: ${SMQ_AUTH_GRPC_CLIENT_CERT:+/auth-grpc-client.crt}
      SMQ_AUTH_GRPC_CLIENT_KEY: ${SMQ_AUTH_GRPC_CLIENT_KEY:+/auth-grpc-client.key}
      SMQ_AUTH_GRPC_SERVER_CA_CERTS: ${SMQ_AUTH_GRPC_SERVER_CA_CERTS:+/auth-grpc-server-ca.crt}
      SMQ_EMAIL_USERNAME: ${SMQ_EMAIL_USERNAME}
      SMQ_EMAIL_PASSWORD: ${SMQ_EMAIL_PASSWORD}
      SMQ_EMAIL_HOST: ${SMQ_EMAIL_HOST}
      SMQ_EMAIL_PORT: ${SMQ_EMAIL_PORT}
      SMQ_EMAIL_FROM_ADDRESS: ${SMQ_EMAIL_FROM_ADDRESS}
      SMQ_EMAIL_FROM_NAME: ${SMQ_EMAIL_FROM_NAME}
      SMQ_EMAIL_TEMPLATE: ${SMQ_SMTP_NOTIFIER_EMAIL_TEMPLATE}
      SMQ_MESSAGE_BROKER_URL: ${SMQ_MESSAGE_BROKER_URL}
      SMQ_JAEGER_URL: ${SMQ_JAEGER_URL}
      SMQ_JAEGER_TRACE_RATIO: ${SMQ_JAEGER_TRACE_RATIO}
      SMQ_SEND_TELEMETRY: ${SMQ_SEND_TELEMETRY}
      SMQ_SMTP_NOTIFIER_INSTANCE_ID: ${SMQ_SMTP_NOTIFIER_INSTANCE_ID}
    ports:
      - ${SMQ_SMTP_NOTIFIER_HTTP_PORT}:${SMQ_SMTP_NOTIFIER_HTTP_PORT}
    networks:
      - supermq-base-net
    volumes:
      - ./config.toml:/config.toml
      - ../templates/${SMQ_SMTP_NOTIFIER_EMAIL_TEMPLATE}:/${SMQ_SMTP_NOTIFIER_EMAIL_TEMPLATE}
      - type: bind
        source: ${SMQ_AUTH_GRPC_CLIENT_CERT:-ssl/certs/dummy/client_cert}
        target: /auth-grpc-client${SMQ_AUTH_GRPC_CLIENT_CERT:+.crt}
        bind:
          create_host_path: true
      - type: bind
        source: ${SMQ_AUTH_GRPC_CLIENT_KEY:-ssl/certs/dummy/client_key}
        target: /auth-grpc-client${SMQ_AUTH_GRPC_CLIENT_KEY:+.key}
        bind:
          create_host_path: true
      - type: bind
        source: ${SMQ_AUTH_GRPC_SERVER_CA_CERTS:-ssl/certs/dummy/server_ca}
        target: /auth-grpc-server-ca${SMQ_AUTH_GRPC_SERVER_CA_CERTS:+.crt}
        bind:
          create_host_path: true
