# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional InfluxDB and InfluxDB-writer services
# for the SupeMQ platform. Since this services are optional, this file is dependent on the
# docker-compose.yml file from <project_root>/docker/. In order to run these services,
# core services, as well as the network from the core composition, should be already running.

networks:
  supermq-base-net:

volumes:
  supermq-contrib-smpp-notifier-volume:

services:
  smpp-notifier-db:
    image: postgres:16.2-alpine
    container_name: supermq-contrib-smpp-notifier-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${SMQ_SMPP_NOTIFIER_DB_USER}
      POSTGRES_PASSWORD: ${SMQ_SMPP_NOTIFIER_DB_PASS}
      POSTGRES_DB: ${SMQ_SMPP_NOTIFIER_DB_NAME}
    networks:
      - supermq-base-net
    volumes:
      - supermq-contrib-smpp-notifier-volume:/var/lib/postgresql/data

  smpp-notifier:
    image: supermq-contrib/smpp-notifier:latest
    container_name: supermq-contrib-smpp-notifier
    depends_on:
      - smpp-notifier-db
    restart: on-failure
    environment:
      SMQ_SMPP_NOTIFIER_LOG_LEVEL: ${SMQ_SMPP_NOTIFIER_LOG_LEVEL}
      SMQ_SMPP_NOTIFIER_FROM_ADDR: ${SMQ_SMPP_NOTIFIER_FROM_ADDR}]
      SMQ_SMPP_NOTIFIER_CONFIG_PATH: ${SMQ_SMPP_NOTIFIER_CONFIG_PATH}
      SMQ_SMPP_NOTIFIER_HTTP_HOST: ${SMQ_SMPP_NOTIFIER_HTTP_HOST}
      SMQ_SMPP_NOTIFIER_HTTP_PORT: ${SMQ_SMPP_NOTIFIER_HTTP_PORT}
      SMQ_SMPP_NOTIFIER_HTTP_SERVER_CERT: ${SMQ_SMPP_NOTIFIER_HTTP_SERVER_CERT}
      SMQ_SMPP_NOTIFIER_HTTP_SERVER_KEY: ${SMQ_SMPP_NOTIFIER_HTTP_SERVER_KEY}
      SMQ_SMPP_NOTIFIER_DB_HOST: ${SMQ_SMPP_NOTIFIER_DB_HOST}
      SMQ_SMPP_NOTIFIER_DB_PORT: ${SMQ_SMPP_NOTIFIER_DB_PORT}
      SMQ_SMPP_NOTIFIER_DB_USER: ${SMQ_SMPP_NOTIFIER_DB_USER}
      SMQ_SMPP_NOTIFIER_DB_PASS: ${SMQ_SMPP_NOTIFIER_DB_PASS}
      SMQ_SMPP_NOTIFIER_DB_NAME: ${SMQ_SMPP_NOTIFIER_DB_NAME}
      SMQ_SMPP_NOTIFIER_DB_SSL_MODE: ${SMQ_SMPP_NOTIFIER_DB_SSL_MODE}
      SMQ_SMPP_NOTIFIER_DB_SSL_CERT: ${SMQ_SMPP_NOTIFIER_DB_SSL_CERT}
      SMQ_SMPP_NOTIFIER_DB_SSL_KEY: ${SMQ_SMPP_NOTIFIER_DB_SSL_KEY}
      SMQ_SMPP_NOTIFIER_DB_SSL_ROOT_CERT: ${SMQ_SMPP_NOTIFIER_DB_SSL_ROOT_CERT}
      SMQ_SMPP_ADDRESS: ${SMQ_SMPP_ADDRESS}
      SMQ_SMPP_USERNAME: ${SMQ_SMPP_USERNAME}
      SMQ_SMPP_PASSWORD: ${SMQ_SMPP_PASSWORD}
      SMQ_SMPP_SYSTEM_TYPE: ${SMQ_SMPP_SYSTEM_TYPE}
      SMQ_SMPP_SRC_ADDR_TON: ${SMQ_SMPP_SRC_ADDR_TON}
      SMQ_SMPP_SRC_ADDR_NPI: ${SMQ_SMPP_SRC_ADDR_NPI}
      SMQ_SMPP_DST_ADDR_TON: ${SMQ_SMPP_DST_ADDR_TON}
      SMQ_SMPP_DST_ADDR_NPI: ${SMQ_SMPP_DST_ADDR_NPI}
      SMQ_AUTH_GRPC_URL: ${SMQ_AUTH_GRPC_URL}
      SMQ_AUTH_GRPC_TIMEOUT: ${SMQ_AUTH_GRPC_TIMEOUT}
      SMQ_AUTH_GRPC_CLIENT_CERT: ${SMQ_AUTH_GRPC_CLIENT_CERT:+/auth-grpc-client.crt}
      SMQ_AUTH_GRPC_CLIENT_KEY: ${SMQ_AUTH_GRPC_CLIENT_KEY:+/auth-grpc-client.key}
      SMQ_AUTH_GRPC_SERVER_CA_CERTS: ${SMQ_AUTH_GRPC_SERVER_CA_CERTS:+/auth-grpc-server-ca.crt}
      SMQ_MESSAGE_BROKER_URL: ${SMQ_MESSAGE_BROKER_URL}
      SMQ_JAEGER_URL: ${SMQ_JAEGER_URL}
      SMQ_JAEGER_TRACE_RATIO: ${SMQ_JAEGER_TRACE_RATIO}
      SMQ_SEND_TELEMETRY: ${SMQ_SEND_TELEMETRY}
      SMQ_SMPP_NOTIFIER_INSTANCE_ID: ${SMQ_SMPP_NOTIFIER_INSTANCE_ID}
    ports:
      - ${SMQ_SMPP_NOTIFIER_HTTP_PORT}:${SMQ_SMPP_NOTIFIER_HTTP_PORT}
    networks:
      - supermq-base-net
    volumes:
      - ./config.toml:/config.toml
      # Auth gRPC client certificates
      - type: bind
        source: ${SMQ_ADDONS_CERTS_PATH_PREFIX}${SMQ_AUTH_GRPC_CLIENT_CERT:-./ssl/certs/dummy/client_cert}
        target: /auth-grpc-client${SMQ_AUTH_GRPC_CLIENT_CERT:+.crt}
        bind:
          create_host_path: true
      - type: bind
        source: ${SMQ_ADDONS_CERTS_PATH_PREFIX}${SMQ_AUTH_GRPC_CLIENT_KEY:-./ssl/certs/dummy/client_key}
        target: /auth-grpc-client${SMQ_AUTH_GRPC_CLIENT_KEY:+.key}
        bind:
          create_host_path: true
      - type: bind
        source: ${SMQ_ADDONS_CERTS_PATH_PREFIX}${SMQ_AUTH_GRPC_SERVER_CA_CERTS:-./ssl/certs/dummy/server_ca}
        target: /auth-grpc-server-ca${SMQ_AUTH_GRPC_SERVER_CA_CERTS:+.crt}
        bind:
          create_host_path: true
