// Code generated by mockery v2.43.2. DO NOT EDIT.

// Copyright (c) Abstract Machines

package mocks

import (
	context "context"

	authn "github.com/absmach/supermq/pkg/authn"

	mock "github.com/stretchr/testify/mock"

	notifiers "github.com/absmach/supermq-contrib/consumers/notifiers"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// ConsumeBlocking provides a mock function with given fields: ctx, messages
func (_m *Service) ConsumeBlocking(ctx context.Context, messages interface{}) error {
	ret := _m.Called(ctx, messages)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeBlocking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, messages)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSubscription provides a mock function with given fields: ctx, session, sub
func (_m *Service) CreateSubscription(ctx context.Context, session authn.Session, sub notifiers.Subscription) (notifiers.Subscription, error) {
	ret := _m.Called(ctx, session, sub)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubscription")
	}

	var r0 notifiers.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, authn.Session, notifiers.Subscription) (notifiers.Subscription, error)); ok {
		return rf(ctx, session, sub)
	}
	if rf, ok := ret.Get(0).(func(context.Context, authn.Session, notifiers.Subscription) notifiers.Subscription); ok {
		r0 = rf(ctx, session, sub)
	} else {
		r0 = ret.Get(0).(notifiers.Subscription)
	}

	if rf, ok := ret.Get(1).(func(context.Context, authn.Session, notifiers.Subscription) error); ok {
		r1 = rf(ctx, session, sub)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSubscriptions provides a mock function with given fields: ctx, sesssion, pm
func (_m *Service) ListSubscriptions(ctx context.Context, sesssion authn.Session, pm notifiers.PageMetadata) (notifiers.Page, error) {
	ret := _m.Called(ctx, sesssion, pm)

	if len(ret) == 0 {
		panic("no return value specified for ListSubscriptions")
	}

	var r0 notifiers.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, authn.Session, notifiers.PageMetadata) (notifiers.Page, error)); ok {
		return rf(ctx, sesssion, pm)
	}
	if rf, ok := ret.Get(0).(func(context.Context, authn.Session, notifiers.PageMetadata) notifiers.Page); ok {
		r0 = rf(ctx, sesssion, pm)
	} else {
		r0 = ret.Get(0).(notifiers.Page)
	}

	if rf, ok := ret.Get(1).(func(context.Context, authn.Session, notifiers.PageMetadata) error); ok {
		r1 = rf(ctx, sesssion, pm)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveSubscription provides a mock function with given fields: ctx, session, id
func (_m *Service) RemoveSubscription(ctx context.Context, session authn.Session, id string) error {
	ret := _m.Called(ctx, session, id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, authn.Session, string) error); ok {
		r0 = rf(ctx, session, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ViewSubscription provides a mock function with given fields: ctx, session, id
func (_m *Service) ViewSubscription(ctx context.Context, session authn.Session, id string) (notifiers.Subscription, error) {
	ret := _m.Called(ctx, session, id)

	if len(ret) == 0 {
		panic("no return value specified for ViewSubscription")
	}

	var r0 notifiers.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, authn.Session, string) (notifiers.Subscription, error)); ok {
		return rf(ctx, session, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, authn.Session, string) notifiers.Subscription); ok {
		r0 = rf(ctx, session, id)
	} else {
		r0 = ret.Get(0).(notifiers.Subscription)
	}

	if rf, ok := ret.Get(1).(func(context.Context, authn.Session, string) error); ok {
		r1 = rf(ctx, session, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
