# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional MongoDB and MongoDB-writer services
# for SupeMQ platform. Since these are optional, this file is dependent of docker-compose file
# from <project_root>/docker. In order to run these services, execute command:
# docker compose -f docker/docker-compose.yml -f docker/addons/mongodb-writer/docker-compose.yml up
# from project root. MongoDB default port (27017) is exposed, so you can use various tools for database
# inspection and data visualization.

networks:
  supermq-base-net:

volumes:
  supermq-contrib-mongodb-db-volume:
  supermq-contrib-mongodb-configdb-volume:

services:
  mongodb:
    image: mongo:7.0.8
    container_name: supermq-contrib-mongodb
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: ${SMQ_MONGO_NAME}
    ports:
      - ${SMQ_MONGO_PORT}:${SMQ_MONGO_PORT}
    networks:
      - supermq-base-net
    volumes:
      - supermq-contrib-mongodb-db-volume:/data/db
      - supermq-contrib-mongodb-configdb-volume:/data/configdb

  mongodb-writer:
    image: supermq-contrib/mongodb-writer:${SMQ_RELEASE_TAG}
    container_name: supermq-contrib-mongodb-writer
    depends_on:
      - mongodb
    restart: on-failure
    environment:
      SMQ_MONGO_WRITER_LOG_LEVEL: ${SMQ_MONGO_WRITER_LOG_LEVEL}
      SMQ_MONGO_WRITER_CONFIG_PATH: ${SMQ_MONGO_WRITER_CONFIG_PATH}
      SMQ_MONGO_WRITER_HTTP_HOST: ${SMQ_MONGO_WRITER_HTTP_HOST}
      SMQ_MONGO_WRITER_HTTP_PORT: ${SMQ_MONGO_WRITER_HTTP_PORT}
      SMQ_MONGO_WRITER_HTTP_SERVER_CERT: ${SMQ_MONGO_WRITER_HTTP_SERVER_CERT}
      SMQ_MONGO_WRITER_HTTP_SERVER_KEY: ${SMQ_MONGO_WRITER_HTTP_SERVER_KEY}
      SMQ_MONGO_HOST: ${SMQ_MONGO_HOST}
      SMQ_MONGO_PORT: ${SMQ_MONGO_PORT}
      SMQ_MONGO_NAME: ${SMQ_MONGO_NAME}
      SMQ_MESSAGE_BROKER_URL: ${SMQ_MESSAGE_BROKER_URL}
      SMQ_JAEGER_URL: ${SMQ_JAEGER_URL}
      SMQ_JAEGER_TRACE_RATIO: ${SMQ_JAEGER_TRACE_RATIO}
      SMQ_SEND_TELEMETRY: ${SMQ_SEND_TELEMETRY}
      SMQ_MONGO_WRITER_INSTANCE_ID: ${SMQ_MONGO_WRITER_INSTANCE_ID}
    ports:
      - ${SMQ_MONGO_WRITER_HTTP_PORT}:${SMQ_MONGO_WRITER_HTTP_PORT}
    networks:
      - supermq-base-net
    volumes:
      - ./config.toml:/config.toml
